apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidently
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evidently
  template:
    metadata:
      labels:
        app: evidently
    spec:
      containers:
        - name: evidently
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8001