apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-service-account
  annotations:
    serving.kserve.io/s3-endpoint: s3.ap-southeast-1.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: ap-southeast-1
secrets:
  - name: s3-credentials